'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module GlobalStrings
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PSO2_Tweaker.GlobalStrings", GetType(GlobalStrings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All done!.
        '''</summary>
        Friend ReadOnly Property strallDone() As String
            Get
                Return ResourceManager.GetString("strallDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All done - System ready!.
        '''</summary>
        Friend ReadOnly Property strAllDoneSystemReady() As String
            Get
                Return ResourceManager.GetString("strAllDoneSystemReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All files checked out!.
        '''</summary>
        Friend ReadOnly Property strAllFilesCheckedOut() As String
            Get
                Return ResourceManager.GetString("strAllFilesCheckedOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All necessary files restored!.
        '''</summary>
        Friend ReadOnly Property strAllNecessaryFiles() As String
            Get
                Return ResourceManager.GetString("strAllNecessaryFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always on Top.
        '''</summary>
        Friend ReadOnly Property strAlwaysonTop() As String
            Get
                Return ResourceManager.GetString("strAlwaysonTop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Analyze Install for Issues.
        '''</summary>
        Friend ReadOnly Property strAnalyzeInstallforIssues() As String
            Get
                Return ResourceManager.GetString("strAnalyzeInstallforIssues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  and the latest is .
        '''</summary>
        Friend ReadOnly Property strAndthelatestis() As String
            Get
                Return ResourceManager.GetString("strAndthelatestis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply Selected Changes.
        '''</summary>
        Friend ReadOnly Property strApplySelectedChanges() As String
            Get
                Return ResourceManager.GetString("strApplySelectedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to reset all of PSO2&apos;s settings? This includes preferences, auto-login, preferred ships, etc..
        '''</summary>
        Friend ReadOnly Property strAreYouSureResetPSO2Settings() As String
            Get
                Return ResourceManager.GetString("strAreYouSureResetPSO2Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you wish to continue? This will restore your backup from before you applied this patch..
        '''</summary>
        Friend ReadOnly Property strAreYouSureRestoreBackup() As String
            Get
                Return ResourceManager.GetString("strAreYouSureRestoreBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you SURE you selected the pso2_bin folder?.
        '''</summary>
        Friend ReadOnly Property strAreYouSurewin32() As String
            Get
                Return ResourceManager.GetString("strAreYouSurewin32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you SURE you selected the pso2_bin and not a folder inside it?.
        '''</summary>
        Friend ReadOnly Property strAreYouSurewin32NotInside() As String
            Get
                Return ResourceManager.GetString("strAreYouSurewin32NotInside", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-installing EN patch....
        '''</summary>
        Friend ReadOnly Property strAutoInstallingENPatch() As String
            Get
                Return ResourceManager.GetString("strAutoInstallingENPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-installing Large Files....
        '''</summary>
        Friend ReadOnly Property strAutoInstallingLF() As String
            Get
                Return ResourceManager.GetString("strAutoInstallingLF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto-installing Story Patch....
        '''</summary>
        Friend ReadOnly Property strAutoInstallingStoryPatch() As String
            Get
                Return ResourceManager.GetString("strAutoInstallingStoryPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous Pre-EN patch backups..
        '''</summary>
        Friend ReadOnly Property strBackupEN() As String
            Get
                Return ResourceManager.GetString("strBackupEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Backup restored!.
        '''</summary>
        Friend ReadOnly Property strBackupRestored() As String
            Get
                Return ResourceManager.GetString("strBackupRestored", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginning Story Mode Update....
        '''</summary>
        Friend ReadOnly Property strBeginningStoryModeUpdate() As String
            Get
                Return ResourceManager.GetString("strBeginningStoryModeUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel Current Download.
        '''</summary>
        Friend ReadOnly Property strCancelCurrentDownload() As String
            Get
                Return ResourceManager.GetString("strCancelCurrentDownload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot find resume file - Please try patching again!.
        '''</summary>
        Friend ReadOnly Property strCannotFindResume() As String
            Get
                Return ResourceManager.GetString("strCannotFindResume", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t find backup directory - Should be .
        '''</summary>
        Friend ReadOnly Property strCantFindBackupDirectory() As String
            Get
                Return ResourceManager.GetString("strCantFindBackupDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changes:.
        '''</summary>
        Friend ReadOnly Property strChanges() As String
            Get
                Return ResourceManager.GetString("strChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for Deleted/Empty Files.
        '''</summary>
        Friend ReadOnly Property strCheckforDeletedMissingFiles() As String
            Get
                Return ResourceManager.GetString("strCheckforDeletedMissingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for missing files.
        '''</summary>
        Friend ReadOnly Property strCheckformissingfiles() As String
            Get
                Return ResourceManager.GetString("strCheckformissingfiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for Old/Missing Files.
        '''</summary>
        Friend ReadOnly Property strCheckForOldMissingFiles() As String
            Get
                Return ResourceManager.GetString("strCheckForOldMissingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for PSO2 Updates (Old Method).
        '''</summary>
        Friend ReadOnly Property strCheckforPSO2Updates() As String
            Get
                Return ResourceManager.GetString("strCheckforPSO2Updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check for Story Patch Updates.
        '''</summary>
        Friend ReadOnly Property strCheckForStoryPatchUpdates() As String
            Get
                Return ResourceManager.GetString("strCheckForStoryPatchUpdates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking connection to Patch Server....
        '''</summary>
        Friend ReadOnly Property strCheckingConnection() As String
            Get
                Return ResourceManager.GetString("strCheckingConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking files....
        '''</summary>
        Friend ReadOnly Property strCheckingFiles() As String
            Get
                Return ResourceManager.GetString("strCheckingFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for all files....
        '''</summary>
        Friend ReadOnly Property strCheckingforAllFiles() As String
            Get
                Return ResourceManager.GetString("strCheckingforAllFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for folders....
        '''</summary>
        Friend ReadOnly Property strCheckingForFolders() As String
            Get
                Return ResourceManager.GetString("strCheckingForFolders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for missing/old files....
        '''</summary>
        Friend ReadOnly Property strCheckingForMissingOldFiles() As String
            Get
                Return ResourceManager.GetString("strCheckingForMissingOldFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for necessary files....
        '''</summary>
        Friend ReadOnly Property strCheckingForNecessaryFiles() As String
            Get
                Return ResourceManager.GetString("strCheckingForNecessaryFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for new content....
        '''</summary>
        Friend ReadOnly Property strCheckingforNewContent() As String
            Get
                Return ResourceManager.GetString("strCheckingforNewContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for PSO2 Updates....
        '''</summary>
        Friend ReadOnly Property strCheckingforPSO2Updates() As String
            Get
                Return ResourceManager.GetString("strCheckingforPSO2Updates", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for updates, please wait a moment....
        '''</summary>
        Friend ReadOnly Property strCheckingforupdatesPleasewaitamoment() As String
            Get
                Return ResourceManager.GetString("strCheckingforupdatesPleasewaitamoment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for updates to patches....
        '''</summary>
        Friend ReadOnly Property strCheckingforUpdatestopatches() As String
            Get
                Return ResourceManager.GetString("strCheckingforUpdatestopatches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story Patch Server:.
        '''</summary>
        Friend ReadOnly Property strChooseABackgroundImage() As String
            Get
                Return ResourceManager.GetString("strChooseABackgroundImage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose a language:.
        '''</summary>
        Friend ReadOnly Property strChooseALanguage() As String
            Get
                Return ResourceManager.GetString("strChooseALanguage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose a theme:.
        '''</summary>
        Friend ReadOnly Property strChooseATheme() As String
            Get
                Return ResourceManager.GetString("strChooseATheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click the ORB to access the menu.
        '''</summary>
        Friend ReadOnly Property strClickOrb() As String
            Get
                Return ResourceManager.GetString("strClickOrb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find pso2.exe! Are you sure you selected the right directory?.
        '''</summary>
        Friend ReadOnly Property strCouldNotFindPSO2() As String
            Get
                Return ResourceManager.GetString("strCouldNotFindPSO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not find pso2.exe - This can usually be solved by going to Troubleshooting -&gt; Fix PSO2 EXEs.
        '''</summary>
        Friend ReadOnly Property strCouldNotFindPSO2EXE() As String
            Get
                Return ResourceManager.GetString("strCouldNotFindPSO2EXE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Creating backup directory...
        '''</summary>
        Friend ReadOnly Property strCreatingBackupDirectory() As String
            Get
                Return ResourceManager.GetString("strCreatingBackupDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current EN Patch version is: .
        '''</summary>
        Friend ReadOnly Property strCurrentENPatchis() As String
            Get
                Return ResourceManager.GetString("strCurrentENPatchis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Large Files version is: .
        '''</summary>
        Friend ReadOnly Property strCurrentLargeFilesis() As String
            Get
                Return ResourceManager.GetString("strCurrentLargeFilesis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currently checking file #.
        '''</summary>
        Friend ReadOnly Property strCurrentlyCheckingFile() As String
            Get
                Return ResourceManager.GetString("strCurrentlyCheckingFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Currently Selected Directory:.
        '''</summary>
        Friend ReadOnly Property strCurrentlyselecteddirectory() As String
            Get
                Return ResourceManager.GetString("strCurrentlyselecteddirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current OS Full name: .
        '''</summary>
        Friend ReadOnly Property strCurrentOSFullName() As String
            Get
                Return ResourceManager.GetString("strCurrentOSFullName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current OS Version: .
        '''</summary>
        Friend ReadOnly Property strCurrentOSVersion() As String
            Get
                Return ResourceManager.GetString("strCurrentOSVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Story Patch version is: .
        '''</summary>
        Friend ReadOnly Property strCurrentStoryPatchis() As String
            Get
                Return ResourceManager.GetString("strCurrentStoryPatchis", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deleting item_name_cache.dat file to prevent issues with vanilla PSO2....
        '''</summary>
        Friend ReadOnly Property strDeletingItemCache() As String
            Get
                Return ResourceManager.GetString("strDeletingItemCache", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnose Connection Issues.
        '''</summary>
        Friend ReadOnly Property strDiagnoseConnectionIssues() As String
            Get
                Return ResourceManager.GetString("strDiagnoseConnectionIssues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you have the latest version of PSO2 before today? As in, could you connect to the server yesterday and play fine? If so, hit yes to only download the new content. Otherwise, hit no to scan all files..
        '''</summary>
        Friend ReadOnly Property strDidYouHaveTheLatestVersion() As String
            Get
                Return ResourceManager.GetString("strDidYouHaveTheLatestVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Does the item patch work with the newest PSO2 version?: .
        '''</summary>
        Friend ReadOnly Property strDoesItemPatchWork() As String
            Get
                Return ResourceManager.GetString("strDoesItemPatchWork", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done!.
        '''</summary>
        Friend ReadOnly Property strDone() As String
            Get
                Return ResourceManager.GetString("strDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done testing! If you got any errors here, please carry out the recommended steps..
        '''</summary>
        Friend ReadOnly Property strDoneTesting() As String
            Get
                Return ResourceManager.GetString("strDoneTesting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download complete! (Downloaded .
        '''</summary>
        Friend ReadOnly Property strDownloadCompleteDownloaded() As String
            Get
                Return ResourceManager.GetString("strDownloadCompleteDownloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloaded .
        '''</summary>
        Friend ReadOnly Property strDownloaded() As String
            Get
                Return ResourceManager.GetString("strDownloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloaded and installed .
        '''</summary>
        Friend ReadOnly Property strDownloadedandInstalled() As String
            Get
                Return ResourceManager.GetString("strDownloadedandInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloaded a total of .
        '''</summary>
        Friend ReadOnly Property strDownloadedATotalOf() As String
            Get
                Return ResourceManager.GetString("strDownloadedATotalOf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading .
        '''</summary>
        Friend ReadOnly Property strDownloading() As String
            Get
                Return ResourceManager.GetString("strDownloading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading EN patch to prepare for uninstall....
        '''</summary>
        Friend ReadOnly Property strDownloadingENToUninstall() As String
            Get
                Return ResourceManager.GetString("strDownloadingENToUninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading latest item translation files....
        '''</summary>
        Friend ReadOnly Property strDownloadingItemTranslationFiles() As String
            Get
                Return ResourceManager.GetString("strDownloadingItemTranslationFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading latest item translation files....
        '''</summary>
        Friend ReadOnly Property strDownloadingLatestItemTranslationFiles() As String
            Get
                Return ResourceManager.GetString("strDownloadingLatestItemTranslationFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Latest patch files....
        '''</summary>
        Friend ReadOnly Property strDownloadingLatestPatchFiles() As String
            Get
                Return ResourceManager.GetString("strDownloadingLatestPatchFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Large Files to prepare for uninstall....
        '''</summary>
        Friend ReadOnly Property strDownloadingLFToUninstall() As String
            Get
                Return ResourceManager.GetString("strDownloadingLFToUninstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Patch file #1....
        '''</summary>
        Friend ReadOnly Property strDownloadingPatchFile1() As String
            Get
                Return ResourceManager.GetString("strDownloadingPatchFile1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Patch file #2....
        '''</summary>
        Friend ReadOnly Property strDownloadingPatchFile2() As String
            Get
                Return ResourceManager.GetString("strDownloadingPatchFile2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Patch file #3....
        '''</summary>
        Friend ReadOnly Property strDownloadingPatchFile3() As String
            Get
                Return ResourceManager.GetString("strDownloadingPatchFile3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Patch file #4....
        '''</summary>
        Friend ReadOnly Property strDownloadingPatchFile4() As String
            Get
                Return ResourceManager.GetString("strDownloadingPatchFile4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading .
        '''</summary>
        Friend ReadOnly Property strDownloadingTestFile() As String
            Get
                Return ResourceManager.GetString("strDownloadingTestFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Downloading Update....
        '''</summary>
        Friend ReadOnly Property strDownloadingUpdate() As String
            Get
                Return ResourceManager.GetString("strDownloadingUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please download the story patch at http://arks-layer.com/story.php first!.
        '''</summary>
        Friend ReadOnly Property strDownloadStoryPatch() As String
            Get
                Return ResourceManager.GetString("strDownloadStoryPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download was canceled by user!.
        '''</summary>
        Friend ReadOnly Property strDownloadwasCancelled() As String
            Get
                Return ResourceManager.GetString("strDownloadwasCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EN backup found, restoring....
        '''</summary>
        Friend ReadOnly Property strENBackupFound() As String
            Get
                Return ResourceManager.GetString("strENBackupFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English patch uninstalled!.
        '''</summary>
        Friend ReadOnly Property strENPatchUninstalled() As String
            Get
                Return ResourceManager.GetString("strENPatchUninstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing previous backup....
        '''</summary>
        Friend ReadOnly Property strErasingPreviousBackup() As String
            Get
                Return ResourceManager.GetString("strErasingPreviousBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ERROR - .
        '''</summary>
        Friend ReadOnly Property strERROR() As String
            Get
                Return ResourceManager.GetString("strERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property strExit() As String
            Get
                Return ResourceManager.GetString("strExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extracting to .
        '''</summary>
        Friend ReadOnly Property strExtractingTo() As String
            Get
                Return ResourceManager.GetString("strExtractingTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  [FAILED!].
        '''</summary>
        Friend ReadOnly Property strFAILED() As String
            Get
                Return ResourceManager.GetString("strFAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to get the update information. Usually, this means AIDA broke something. Please DO NOT panic, as the rest of the program will work fine. There is no need to report this error either..
        '''</summary>
        Friend ReadOnly Property strFailedToGetUpdateInfo() As String
            Get
                Return ResourceManager.GetString("strFailedToGetUpdateInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Censor file does not exist. Are you already un-censored?.
        '''</summary>
        Friend ReadOnly Property strFailedToRemoveCensor() As String
            Get
                Return ResourceManager.GetString("strFailedToRemoveCensor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NVidia Logo Video File does not exist. Did you already remove it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRemoveNVidia() As String
            Get
                Return ResourceManager.GetString("strFailedToRemoveNVidia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PC Opening Video File does not exist. Did you already remove it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRemovePC() As String
            Get
                Return ResourceManager.GetString("strFailedToRemovePC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEGA Logo Video File does not exist. Did you already remove it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRemoveSEGA() As String
            Get
                Return ResourceManager.GetString("strFailedToRemoveSEGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vita Opening Video File does not exist. Did you already remove it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRemoveVita() As String
            Get
                Return ResourceManager.GetString("strFailedToRemoveVita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Censor backup file does not exist. Are you already censored?.
        '''</summary>
        Friend ReadOnly Property strFailedToRestoreCensor() As String
            Get
                Return ResourceManager.GetString("strFailedToRestoreCensor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NVidia Logo Video File backup does not exist. Did you already restore it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRestoreNVidia() As String
            Get
                Return ResourceManager.GetString("strFailedToRestoreNVidia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PC Opening Video File backup does not exist. Did you already restore it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRestorePC() As String
            Get
                Return ResourceManager.GetString("strFailedToRestorePC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SEGA Logo Video File backup does not exist. Did you already restore it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRestoreSEGA() As String
            Get
                Return ResourceManager.GetString("strFailedToRestoreSEGA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vita Opening Video File backup does not exist. Did you already restore it?.
        '''</summary>
        Friend ReadOnly Property strFailedToRestoreVita() As String
            Get
                Return ResourceManager.GetString("strFailedToRestoreVita", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This appears to be the first time you&apos;ve used the new version of PSO2 Tweaker - Please select your language and theme in the next window..
        '''</summary>
        Friend ReadOnly Property strFirstTime() As String
            Get
                Return ResourceManager.GetString("strFirstTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fix Gameguard Errors.
        '''</summary>
        Friend ReadOnly Property strFixGameguardErrors() As String
            Get
                Return ResourceManager.GetString("strFixGameguardErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixing permissions for .
        '''</summary>
        Friend ReadOnly Property strFixingPermissionsFor() As String
            Get
                Return ResourceManager.GetString("strFixingPermissionsFor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will fix permission issues with PSO2. First, open the pso2updater.exe, so that it gives you the error &quot;has canceled the launch of pso2updater.exe. file is not updated.&quot;. Do NOT Hit OK. Leave that screen up, and hit OK here instead. It will performing some fixes. A message will pop up with more information when it&apos;s done..
        '''</summary>
        Friend ReadOnly Property strFixPermissionIssuesText() As String
            Get
                Return ResourceManager.GetString("strFixPermissionIssuesText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permissions fixed! NOW you can hit OK on the pso2updater.exe message - it should allow the updater to work and fix itself :) Thanks to RappyPerms and jooozek for this information~.
        '''</summary>
        Friend ReadOnly Property strFixPermissionsDone() As String
            Get
                Return ResourceManager.GetString("strFixPermissionsDone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fix PSO2 EXEs.
        '''</summary>
        Friend ReadOnly Property strFixPSO2EXEs() As String
            Get
                Return ResourceManager.GetString("strFixPSO2EXEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fix PSO2 Permissions.
        '''</summary>
        Friend ReadOnly Property strFixPSO2Permissions() As String
            Get
                Return ResourceManager.GetString("strFixPSO2Permissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Found incomplete patch job - resuming job!.
        '''</summary>
        Friend ReadOnly Property strFoundIncompleteJob() As String
            Get
                Return ResourceManager.GetString("strFoundIncompleteJob", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Game updated to latest Vanilla JP version. Don&apos;t forget to re-install the patches!.
        '''</summary>
        Friend ReadOnly Property strGameUpdatedVanilla() As String
            Get
                Return ResourceManager.GetString("strGameUpdatedVanilla", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GameGuard reset to defaults! Now try running Phantasy Star Online 2 - It should update Gameguard when the PSO2 logo comes up..
        '''</summary>
        Friend ReadOnly Property strGGReset() As String
            Get
                Return ResourceManager.GetString("strGGReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Have you already downloaded the Story Patch? If you hit yes, you&apos;ll be prompted to find the RAR file..
        '''</summary>
        Friend ReadOnly Property strHaveyouDownloadedStoryYet() As String
            Get
                Return ResourceManager.GetString("strHaveyouDownloadedStoryYet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If any of the above versions are incorrect, use the override in options to fix them..
        '''</summary>
        Friend ReadOnly Property strIfAboveVersions() As String
            Get
                Return ResourceManager.GetString("strIfAboveVersions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If this is incorrect, use the story patch location reset in options..
        '''</summary>
        Friend ReadOnly Property strIfStoryIncorrect() As String
            Get
                Return ResourceManager.GetString("strIfStoryIncorrect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to If the above numbers are over 400, you have a bad connection to the PSO2 patch servers..
        '''</summary>
        Friend ReadOnly Property strIfTheAboveNumbers() As String
            Get
                Return ResourceManager.GetString("strIfTheAboveNumbers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to installed/Updated!.
        '''</summary>
        Friend ReadOnly Property strInstalledUpdated() As String
            Get
                Return ResourceManager.GetString("strInstalledUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  installed/Updated! Backup is at .
        '''</summary>
        Friend ReadOnly Property strInstalledUpdatedBackup() As String
            Get
                Return ResourceManager.GetString("strInstalledUpdatedBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installing Patch....
        '''</summary>
        Friend ReadOnly Property strInstallingPatch() As String
            Get
                Return ResourceManager.GetString("strInstallingPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Install/Update Patches.
        '''</summary>
        Friend ReadOnly Property strInstallUpdatePatches() As String
            Get
                Return ResourceManager.GetString("strInstallUpdatePatches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  is missing..
        '''</summary>
        Friend ReadOnly Property strIsMissing() As String
            Get
                Return ResourceManager.GetString("strIsMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is the current OS 64-bit? .
        '''</summary>
        Friend ReadOnly Property strIsTheCurrentOS64bit() As String
            Get
                Return ResourceManager.GetString("strIsTheCurrentOS64bit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Is Unrar Available: .
        '''</summary>
        Friend ReadOnly Property strIsUnrarAvailable() As String
            Get
                Return ResourceManager.GetString("strIsUnrarAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item Translation enabled!.
        '''</summary>
        Friend ReadOnly Property strItemTranslationEnabled() As String
            Get
                Return ResourceManager.GetString("strItemTranslationEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sorry, but the item translation is not working with the current version of PSO2! Please uncheck &quot;Translate items&quot; if you wish to launch PSO2 without it..
        '''</summary>
        Friend ReadOnly Property strItemTranslationNotWorking() As String
            Get
                Return ResourceManager.GetString("strItemTranslationNotWorking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It seems that PSO2 is already running. Would you like to close it?.
        '''</summary>
        Friend ReadOnly Property strItSeemsLikePSO2isalready() As String
            Get
                Return ResourceManager.GetString("strItSeemsLikePSO2isalready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to It seems there was an issue starting PSO2, attempting to autofix....
        '''</summary>
        Friend ReadOnly Property strItSeemsThereWasAnError() As String
            Get
                Return ResourceManager.GetString("strItSeemsThereWasAnError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to With the latest gameguard update, Google Chrome works fine with gameguard. You SHOULD NOT use this to launch Chrome anymore, please launch it normally. Thank you..
        '''</summary>
        Friend ReadOnly Property strLatestGG() As String
            Get
                Return ResourceManager.GetString("strLatestGG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launch Chrome in PSO2 Compatibilty Mode.
        '''</summary>
        Friend ReadOnly Property strLaunchChrome() As String
            Get
                Return ResourceManager.GetString("strLaunchChrome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launching Phantasy Star Online 2....
        '''</summary>
        Friend ReadOnly Property strLaunchingPSO2() As String
            Get
                Return ResourceManager.GetString("strLaunchingPSO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Launch PSO2.
        '''</summary>
        Friend ReadOnly Property strLaunchPSO2() As String
            Get
                Return ResourceManager.GetString("strLaunchPSO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large Files backup found, restoring....
        '''</summary>
        Friend ReadOnly Property strLFBackupFound() As String
            Get
                Return ResourceManager.GetString("strLFBackupFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Large Files uninstalled!.
        '''</summary>
        Friend ReadOnly Property strLFUninstalled() As String
            Get
                Return ResourceManager.GetString("strLFUninstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading sidebar page....
        '''</summary>
        Friend ReadOnly Property strLoadingSidebar() As String
            Get
                Return ResourceManager.GetString("strLoadingSidebar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading sidebar page....
        '''</summary>
        Friend ReadOnly Property strLoadingSidebarPage() As String
            Get
                Return ResourceManager.GetString("strLoadingSidebarPage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to missing files Part 1....
        '''</summary>
        Friend ReadOnly Property strMissingFilesPart1() As String
            Get
                Return ResourceManager.GetString("strMissingFilesPart1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to missing files Part 2....
        '''</summary>
        Friend ReadOnly Property strMissingFilesPart2() As String
            Get
                Return ResourceManager.GetString("strMissingFilesPart2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new EN patch update is available - Would you like to download and install it?.
        '''</summary>
        Friend ReadOnly Property strNewENPatch() As String
            Get
                Return ResourceManager.GetString("strNewENPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new Large Files update is available - Would you like to download and install it?.
        '''</summary>
        Friend ReadOnly Property strNewLargeFiles() As String
            Get
                Return ResourceManager.GetString("strNewLargeFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An update for PSO2 is available - Would you like to download and install it?.
        '''</summary>
        Friend ReadOnly Property strNewPSO2Update() As String
            Get
                Return ResourceManager.GetString("strNewPSO2Update", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NOT SWAPPED.
        '''</summary>
        Friend ReadOnly Property strNotSwapped() As String
            Get
                Return ResourceManager.GetString("strNotSwapped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Options.
        '''</summary>
        Friend ReadOnly Property strOptions() As String
            Get
                Return ResourceManager.GetString("strOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other Tasks.
        '''</summary>
        Friend ReadOnly Property strOtherTasks() As String
            Get
                Return ResourceManager.GetString("strOtherTasks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PLEASE BE AWARE: This will launch chrome with it&apos;s built-in sandbox disabled, which decreases it&apos;s security. Please only use this instance of Chrome to browse trusted sites while playing PSO2. (ie. Bumped, cirnopedia, etc).
        '''</summary>
        Friend ReadOnly Property strPleaseBeAwareChrome() As String
            Get
                Return ResourceManager.GetString("strPleaseBeAwareChrome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please be aware that this will fix SOME Gameguard errors, but will not fix all of them. Make sure anything that could possibly &quot;scan&quot; PSO2 is disabled (Firewalls, debuggers, antivirus, Speed boosters, etc)..
        '''</summary>
        Friend ReadOnly Property strPleaseBeAwareGG() As String
            Get
                Return ResourceManager.GetString("strPleaseBeAwareGG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will open two windows - One will be the Tweaker&apos;s thread on PSO-World.com&apos;s forums. The second will be a pastebin page. Please copy the URL of the pastebin page and include it in your post on the Tweaker thread, along with any information that could be useful. Thanks! - AIDA.
        '''</summary>
        Friend ReadOnly Property strPleasecopytheURL() As String
            Get
                Return ResourceManager.GetString("strPleasecopytheURL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please run Troubleshooting -&gt; Fix Gameguard issues!.
        '''</summary>
        Friend ReadOnly Property strPleaseFixGG() As String
            Get
                Return ResourceManager.GetString("strPleaseFixGG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please run Troubleshooting -&gt; Fix PSO2 EXEs!.
        '''</summary>
        Friend ReadOnly Property strPleaseFixPSO2EXEs() As String
            Get
                Return ResourceManager.GetString("strPleaseFixPSO2EXEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please reinstall PSO2 or check that you selected the correct pso2_bin directory!.
        '''</summary>
        Friend ReadOnly Property strPleaseReinstallOrCheck() As String
            Get
                Return ResourceManager.GetString("strPleaseReinstallOrCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the pre-downloaded Large Files RAR file.
        '''</summary>
        Friend ReadOnly Property strPleaseSelectPreDownloaded() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectPreDownloaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the pre-downloaded EN Patch RAR file.
        '''</summary>
        Friend ReadOnly Property strPleaseSelectPreDownloadENRAR() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectPreDownloadENRAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your PSO2&apos;s pso2_bin Directory. It will be saved so you don&apos;t have to select it again..
        '''</summary>
        Friend ReadOnly Property strPleaseSelectPSO2win32dir() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectPSO2win32dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select the PSO2 Story Patch RAR file.
        '''</summary>
        Friend ReadOnly Property strPleaseSelectStoryRAR() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectStoryRAR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your PSO2&apos;s pso2_bin Directory. It will be saved so you don&apos;t have to select it again..
        '''</summary>
        Friend ReadOnly Property strPleaseSelectwin32Dir() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectwin32Dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select your PSO2 pso2_bin folder..
        '''</summary>
        Friend ReadOnly Property strPleaseSelectWin32folder() As String
            Get
                Return ResourceManager.GetString("strPleaseSelectWin32folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Process was canceled by user!.
        '''</summary>
        Friend ReadOnly Property strProcessWasCancelled() As String
            Get
                Return ResourceManager.GetString("strProcessWasCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program opening, running diagnostics....
        '''</summary>
        Friend ReadOnly Property strProgramOpeningRunningDiagnostics() As String
            Get
                Return ResourceManager.GetString("strProgramOpeningRunningDiagnostics", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program opened successfully! Version .
        '''</summary>
        Friend ReadOnly Property strProgramOpeningSuccessfully() As String
            Get
                Return ResourceManager.GetString("strProgramOpeningSuccessfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program started....
        '''</summary>
        Friend ReadOnly Property strProgramStarted() As String
            Get
                Return ResourceManager.GetString("strProgramStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PSO2 Options.
        '''</summary>
        Friend ReadOnly Property strPSO2Options() As String
            Get
                Return ResourceManager.GetString("strPSO2Options", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All PSO2 settings reset to defaults!.
        '''</summary>
        Friend ReadOnly Property strPSO2SettingsReset() As String
            Get
                Return ResourceManager.GetString("strPSO2SettingsReset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Censor File.
        '''</summary>
        Friend ReadOnly Property strRemoveCensorFile() As String
            Get
                Return ResourceManager.GetString("strRemoveCensorFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove NVidia Video.
        '''</summary>
        Friend ReadOnly Property strRemoveNVidiaVideo() As String
            Get
                Return ResourceManager.GetString("strRemoveNVidiaVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove PC Opening.
        '''</summary>
        Friend ReadOnly Property strRemovePCOpening() As String
            Get
                Return ResourceManager.GetString("strRemovePCOpening", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove SEGA Logo Video.
        '''</summary>
        Friend ReadOnly Property strRemoveSEGALogoVideo() As String
            Get
                Return ResourceManager.GetString("strRemoveSEGALogoVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove Vita Opening.
        '''</summary>
        Friend ReadOnly Property strRemoveVitaOpening() As String
            Get
                Return ResourceManager.GetString("strRemoveVitaOpening", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Removing .
        '''</summary>
        Friend ReadOnly Property strRemoving() As String
            Get
                Return ResourceManager.GetString("strRemoving", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset PSO2 Settings.
        '''</summary>
        Friend ReadOnly Property strResetPSO2Settings() As String
            Get
                Return ResourceManager.GetString("strResetPSO2Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Backups.
        '''</summary>
        Friend ReadOnly Property strRestoreBackups() As String
            Get
                Return ResourceManager.GetString("strRestoreBackups", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Censor File.
        '''</summary>
        Friend ReadOnly Property strRestoreCensorFile() As String
            Get
                Return ResourceManager.GetString("strRestoreCensorFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore failed - backup not found! Re-install the english patch to fix it..
        '''</summary>
        Friend ReadOnly Property strRestoreFailedPleaseReinstall() As String
            Get
                Return ResourceManager.GetString("strRestoreFailedPleaseReinstall", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore NVidia Logo.
        '''</summary>
        Friend ReadOnly Property strRestoreNVidiaLogo() As String
            Get
                Return ResourceManager.GetString("strRestoreNVidiaLogo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore PC Opening Video.
        '''</summary>
        Friend ReadOnly Property strRestorePCOpeningVideo() As String
            Get
                Return ResourceManager.GetString("strRestorePCOpeningVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore SEGA Logo Video.
        '''</summary>
        Friend ReadOnly Property strRestoreSEGALogoVideo() As String
            Get
                Return ResourceManager.GetString("strRestoreSEGALogoVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restore Vita Opening Video.
        '''</summary>
        Friend ReadOnly Property strRestoreVitaOpeningVideo() As String
            Get
                Return ResourceManager.GetString("strRestoreVitaOpeningVideo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring .
        '''</summary>
        Friend ReadOnly Property strRestoring() As String
            Get
                Return ResourceManager.GetString("strRestoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restoring backup to .
        '''</summary>
        Friend ReadOnly Property strRestoringBackupTo() As String
            Get
                Return ResourceManager.GetString("strRestoringBackupTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resume Patching.
        '''</summary>
        Friend ReadOnly Property strResumePatching() As String
            Get
                Return ResourceManager.GetString("strResumePatching", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right click for additional options.
        '''</summary>
        Friend ReadOnly Property strRightClickforOptions() As String
            Get
                Return ResourceManager.GetString("strRightClickforOptions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Directory program is running in: .
        '''</summary>
        Friend ReadOnly Property strRunDirectory() As String
            Get
                Return ResourceManager.GetString("strRunDirectory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected &lt;DIRECTORY&gt; as your PSO2 Directory..
        '''</summary>
        Friend ReadOnly Property strSelectedDir() As String
            Get
                Return ResourceManager.GetString("strSelectedDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Selected PSO2 Directory: .
        '''</summary>
        Friend ReadOnly Property strSelectedPSO2win32directory() As String
            Get
                Return ResourceManager.GetString("strSelectedPSO2win32directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select pso2_bin folder....
        '''</summary>
        Friend ReadOnly Property strSelectPSO2win32folder() As String
            Get
                Return ResourceManager.GetString("strSelectPSO2win32folder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select your pso2_bin folder.
        '''</summary>
        Friend ReadOnly Property strSelectPSO2win32folder2() As String
            Get
                Return ResourceManager.GetString("strSelectPSO2win32folder2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to set as your PSO2 Directory..
        '''</summary>
        Friend ReadOnly Property strSetAsYourPSO2() As String
            Get
                Return ResourceManager.GetString("strSetAsYourPSO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong, would you like to upload your logfile so it can be fixed?.
        '''</summary>
        Friend ReadOnly Property strSomethingWentWrongUpload() As String
            Get
                Return ResourceManager.GetString("strSomethingWentWrongUpload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch backup found, restoring....
        '''</summary>
        Friend ReadOnly Property strStoryBackupFound() As String
            Get
                Return ResourceManager.GetString("strStoryBackupFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A new story patch update is available - Would you like to download and install it? PLEASE NOTE: This update assumes you&apos;ve already downloaded and installed the latest story patch available from http://arks-layer.com, which seems to be: .
        '''</summary>
        Friend ReadOnly Property strStoryModeUpdate() As String
            Get
                Return ResourceManager.GetString("strStoryModeUpdate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch installed! Backup is at .
        '''</summary>
        Friend ReadOnly Property strStoryPatchBackup() As String
            Get
                Return ResourceManager.GetString("strStoryPatchBackup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch automatically located at:.
        '''</summary>
        Friend ReadOnly Property strStoryPatchFound() As String
            Get
                Return ResourceManager.GetString("strStoryPatchFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch installed!.
        '''</summary>
        Friend ReadOnly Property strStoryPatchInstalled() As String
            Get
                Return ResourceManager.GetString("strStoryPatchInstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story Patch Server Tests.
        '''</summary>
        Friend ReadOnly Property strStoryPatchServerTests() As String
            Get
                Return ResourceManager.GetString("strStoryPatchServerTests", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch uninstalled!.
        '''</summary>
        Friend ReadOnly Property strStoryPatchUninstalled() As String
            Get
                Return ResourceManager.GetString("strStoryPatchUninstalled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Story patch updated!.
        '''</summary>
        Friend ReadOnly Property strStoryPatchUpdated() As String
            Get
                Return ResourceManager.GetString("strStoryPatchUpdated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swap PC/Vita Openings .
        '''</summary>
        Friend ReadOnly Property strSwapPCVitaOpenings() As String
            Get
                Return ResourceManager.GetString("strSwapPCVitaOpenings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SWAPPED.
        '''</summary>
        Friend ReadOnly Property strSwapped() As String
            Get
                Return ResourceManager.GetString("strSwapped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Swapping openings....
        '''</summary>
        Friend ReadOnly Property strSwappingOpenings() As String
            Get
                Return ResourceManager.GetString("strSwappingOpenings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminate PSO2 Process.
        '''</summary>
        Friend ReadOnly Property strTerminate() As String
            Get
                Return ResourceManager.GetString("strTerminate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminating PSO2 Process with extreme prejudice....
        '''</summary>
        Friend ReadOnly Property strTerminatePSO2() As String
            Get
                Return ResourceManager.GetString("strTerminatePSO2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Testing download speeds....
        '''</summary>
        Friend ReadOnly Property strTestingDownloadSpeeds() As String
            Get
                Return ResourceManager.GetString("strTestingDownloadSpeeds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Translate items.
        '''</summary>
        Friend ReadOnly Property strTranslateItems() As String
            Get
                Return ResourceManager.GetString("strTranslateItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Translation files do NOT match the downloaded ones! Please download them again by restarting the Tweaker..
        '''</summary>
        Friend ReadOnly Property strTranslationFilesDontMatch() As String
            Get
                Return ResourceManager.GetString("strTranslationFilesDontMatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Troubleshooting.
        '''</summary>
        Friend ReadOnly Property strTroubleshooting() As String
            Get
                Return ResourceManager.GetString("strTroubleshooting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninstalling .
        '''</summary>
        Friend ReadOnly Property strUninstalling() As String
            Get
                Return ResourceManager.GetString("strUninstalling", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninstalling patch....
        '''</summary>
        Friend ReadOnly Property strUninstallingPatch() As String
            Get
                Return ResourceManager.GetString("strUninstallingPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uninstall Patches.
        '''</summary>
        Friend ReadOnly Property strUninstallPatches() As String
            Get
                Return ResourceManager.GetString("strUninstallPatches", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updating .
        '''</summary>
        Friend ReadOnly Property strUpdating() As String
            Get
                Return ResourceManager.GetString("strUpdating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for a command.
        '''</summary>
        Friend ReadOnly Property strWaitingforacommand() As String
            Get
                Return ResourceManager.GetString("strWaitingforacommand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waiting for patch to finish extracting....
        '''</summary>
        Friend ReadOnly Property strWaitingforPatch() As String
            Get
                Return ResourceManager.GetString("strWaitingforPatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Web Links.
        '''</summary>
        Friend ReadOnly Property strWebLinks() As String
            Get
                Return ResourceManager.GetString("strWebLinks", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous Pre-Story patch backups.
        '''
        '''THIS IS HIGHLY RECOMMENDED! If you do NOT make a story patch backup, you will need to redownload the entire story patch from SEGA&apos;s servers when the next update hits. This can turn a 25MB update into a 3.25GB update..
        '''</summary>
        Friend ReadOnly Property strWouldYouLikeBackupStory() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeBackupStory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous backups for this patch..
        '''</summary>
        Friend ReadOnly Property strWouldYouLikeToBackupLanguagePatch() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToBackupLanguagePatch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to backup your files before applying the patch? This will erase all previous Pre-Large Files patch backups..
        '''</summary>
        Friend ReadOnly Property strWouldYouLikeToBackupLargeFiles() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToBackupLargeFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to download and install the missing files?.
        '''</summary>
        Friend ReadOnly Property strWouldYouLikeToDownloadInstallMissing() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToDownloadInstallMissing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to . Would you like to download the new version?.
        '''</summary>
        Friend ReadOnly Property strWouldyouliketodownloadthenewversion() As String
            Get
                Return ResourceManager.GetString("strWouldyouliketodownloadthenewversion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Would you like to use a pre-downloaded RAR file containing the patch instead of downloading it now?.
        '''</summary>
        Friend ReadOnly Property strWouldYouLikeToUse() As String
            Get
                Return ResourceManager.GetString("strWouldYouLikeToUse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You appear to have the latest data files - Running final update steps!.
        '''</summary>
        Friend ReadOnly Property strYouAppearToBeUpToDate() As String
            Get
                Return ResourceManager.GetString("strYouAppearToBeUpToDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are using an outdated version of the program. You have version .
        '''</summary>
        Friend ReadOnly Property strYouareusinganoutdatedversionoftheprogram() As String
            Get
                Return ResourceManager.GetString("strYouareusinganoutdatedversionoftheprogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You cannot restore and remove at the same time..
        '''</summary>
        Friend ReadOnly Property strYouCannotRemoveRestore() As String
            Get
                Return ResourceManager.GetString("strYouCannotRemoveRestore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have the latest version of the program: .
        '''</summary>
        Friend ReadOnly Property strYouhavethelatestversionoftheprogram() As String
            Get
                Return ResourceManager.GetString("strYouhavethelatestversionoftheprogram", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your 7za.exe seem to be corrupt, redownloading....
        '''</summary>
        Friend ReadOnly Property strYour7zipiscorrupt() As String
            Get
                Return ResourceManager.GetString("strYour7zipiscorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your download speed is:.
        '''</summary>
        Friend ReadOnly Property strYourDownloadSpeedIs() As String
            Get
                Return ResourceManager.GetString("strYourDownloadSpeedIs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your log file appears to be quite large - Would you like to clear it?.
        '''</summary>
        Friend ReadOnly Property strYourLogFileisHUGE() As String
            Get
                Return ResourceManager.GetString("strYourLogFileisHUGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your translation.bin seem to be corrupt, redownloading....
        '''</summary>
        Friend ReadOnly Property strYourTranslationBINiscorrupt() As String
            Get
                Return ResourceManager.GetString("strYourTranslationBINiscorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your translator.dll seem to be corrupt, redownloading....
        '''</summary>
        Friend ReadOnly Property strYourTranslatorDLLiscorrupt() As String
            Get
                Return ResourceManager.GetString("strYourTranslatorDLLiscorrupt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your UnRar.exe seem to be corrupt, redownloading....
        '''</summary>
        Friend ReadOnly Property strYourUnrariscorrupt() As String
            Get
                Return ResourceManager.GetString("strYourUnrariscorrupt", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
